version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/infra/lambdas"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
    target-branch: "develop"
