#!/usr/bin/env -S node --experimental-strip-types
/**
 * Reads costco_locations_with_regions.csv + costco_coordinates.json (+ more_coords.json
 * as a fallback) and emits web/src/data/locations.ts as a typed array.
 *
 * Run: node --experimental-strip-types scripts/build-locations.ts
 *   or: npx tsx scripts/build-locations.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

type Coords = { lat: number; lng: number }
type CoordTable = Record<string, Coords>

function parseCsv(text: string): string[][] {
  // Minimal CSV parser supporting quoted fields with embedded commas.
  const rows: string[][] = []
  let row: string[] = []
  let cur = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') {
        cur += '"'
        i++
      } else if (c === '"') {
        inQuotes = false
      } else {
        cur += c
      }
    } else {
      if (c === '"') inQuotes = true
      else if (c === ',') {
        row.push(cur)
        cur = ''
      } else if (c === '\n') {
        row.push(cur)
        rows.push(row)
        row = []
        cur = ''
      } else if (c === '\r') {
        // skip
      } else {
        cur += c
      }
    }
  }
  if (cur || row.length) {
    row.push(cur)
    rows.push(row)
  }
  return rows.filter((r) => r.some((cell) => cell.length > 0))
}

const csvText = readFileSync(join(root, 'costco_locations_with_regions.csv'), 'utf8')
const coordsText = readFileSync(join(root, 'costco_coordinates.json'), 'utf8')
const moreCoordsText = readFileSync(join(root, 'more_coords.json'), 'utf8')

const coords: CoordTable = {
  ...(JSON.parse(moreCoordsText) as CoordTable),
  ...(JSON.parse(coordsText) as CoordTable), // primary table wins on conflict
}

const rows = parseCsv(csvText)
const header = rows.shift()
if (!header) throw new Error('empty CSV')

const idx = (name: string) => {
  const i = header.indexOf(name)
  if (i < 0) throw new Error(`missing column: ${name}`)
  return i
}

const NAME = idx('Store Name')
const ADDRESS = idx('Address')
const CITY = idx('City')
const STATE = idx('State')
const ZIP = idx('Zipcode')
const PHONE = idx('Phone')
const URL = idx('URL')
const COUNTRY = idx('Country')
const REGION = idx('Region')

type Location = {
  id: string
  name: string
  address: string
  city: string
  state: string
  zipcode: string
  phone: string
  url: string
  country: string
  region: string
  lat: number
  lng: number
}

const out: Location[] = []
const missing: string[] = []

for (const r of rows) {
  const address = r[ADDRESS]
  const city = r[CITY]
  const state = r[STATE]
  const zip = r[ZIP]
  const key = `${address}, ${city}, ${state} ${zip}`
  const coord = coords[key]
  if (!coord) {
    missing.push(key)
    continue
  }
  // Stable id: country + state + zip + first 8 of address (slug-safe).
  const slug = `${r[COUNTRY]}-${state}-${zip}-${address}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
  out.push({
    id: slug,
    name: r[NAME],
    address,
    city,
    state,
    zipcode: zip,
    phone: r[PHONE],
    url: r[URL],
    country: r[COUNTRY],
    region: r[REGION],
    lat: coord.lat,
    lng: coord.lng,
  })
}

const ids = new Set<string>()
for (const l of out) {
  if (ids.has(l.id)) throw new Error(`duplicate id: ${l.id}`)
  ids.add(l.id)
}

const banner = `// Generated by scripts/build-locations.ts. Do not edit by hand.\n`
const tsBody =
  banner +
  `\nexport type Location = {\n` +
  `  id: string\n  name: string\n  address: string\n  city: string\n  state: string\n` +
  `  zipcode: string\n  phone: string\n  url: string\n  country: string\n  region: string\n` +
  `  lat: number\n  lng: number\n}\n\n` +
  `export const locations: Location[] = ${JSON.stringify(out, null, 2)}\n`

const outPath = join(root, 'web', 'src', 'data', 'locations.ts')
writeFileSync(outPath, tsBody)

console.log(`wrote ${out.length} locations → ${outPath}`)
if (missing.length) {
  console.warn(`skipped ${missing.length} rows missing coordinates:`)
  for (const m of missing.slice(0, 10)) console.warn(`  - ${m}`)
  if (missing.length > 10) console.warn(`  ... and ${missing.length - 10} more`)
}
